//! THIS FILE IS AUTO-GENERATED BY `build.rs`.
//! DO NOT EDIT THIS FILE DIRECTLY.

pub mod icon_set;
#[rustfmt::skip]
pub mod feather_icons;

pub use icon_set::IconSet;
#[rustfmt::skip]
pub use feather_icons::FEATHER_ICONS;

/// All available icon sets.
pub const ALL_ICON_SETS: &[&IconSet] = &[&FEATHER_ICONS];
