import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col items-center p-24">
            <header className="mb-4">
                <h1 className="text-6xl font-bold text-center pb-2">
                    Badge
                    <span className="text-orange-500">RS</span>
                </h1>
                <div className="flex flex-col items-center justify-center">
                    Fast and clean SVG badges for your projects
                </div>
            </header>
            {children}
        </div>
    </body>
    </html>
  )
}
